[theme]
# Primary accent color for interactive elements.
primaryColor = "#565B38"

# Background color for the main content area.
backgroundColor = "#BDB1A9"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#AB9586"

# Color used for almost all text.
textColor = "#E7E8E2"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "montserrat"